
export const GET_EXPENSES_REQUEST = 'GET_EXPENSES_REQUEST'
export const GET_EXPENSES_SUCCESS = 'GET_EXPENSES_SUCCESS'
export const GET_EXPENSES_FAILURE = 'GET_EXPENSES_FAILURE'
// Expenses Detail
export const GET_EXPENSE_DETAIL_REQUEST = 'GET_EXPENSE_DETAIL_REQUEST'
export const GET_EXPENSE_DETAIL_SUCCESS = 'GET_EXPENSE_DETAIL_SUCCESS'
export const GET_EXPENSE_DETAIL_FAILURE = 'GET_EXPENSE_DETAIL_FAILURE'
// Add Expenses
export const ADD_EXPENSES_REQUEST = 'ADD_EXPENSES_REQUEST'
export const ADD_EXPENSES_SUCCESS = 'ADD_EXPENSES_SUCCESS'
export const ADD_EXPENSES_FAILURE = 'ADD_EXPENSES_FAILURE'
// Edit Expenses
export const EDIT_EXPENSES_REQUEST = 'EDIT_EXPENSES_REQUEST'
export const EDIT_EXPENSES_SUCCESS = 'EDIT_EXPENSES_SUCCESS'
export const EDIT_EXPENSES_FAILURE = 'EDIT_EXPENSES_FAILURE'
