
export const GET_PAYSLIPS_REQUEST = 'GET_PAYSLIPS_REQUEST'
export const GET_PAYSLIPS_SUCCESS = 'GET_PAYSLIPS_SUCCESS'
export const GET_PAYSLIPS_FAILURE = 'GET_PAYSLIPS_FAILURE'
// Payslips Download
export const DOWNLOAD_PAYSLIP_REQUEST = 'DOWNLOAD_PAYSLIP_REQUEST'
export const DOWNLOAD_PAYSLIP_SUCCESS = 'DOWNLOAD_PAYSLIP_SUCCESS'
export const DOWNLOAD_PAYSLIP_FAILURE = 'DOWNLOAD_PAYSLIP_FAILURE'
