
export const GET_TIMESHEETS_REQUEST = 'GET_TIMESHEETS_REQUEST'
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS'
export const GET_TIMESHEETS_FAILURE = 'GET_TIMESHEETS_FAILURE'
// Asignment Detail

export const GET_TIMESHEET_DETAIL_REQUEST = 'GET_TIMESHEET_DETAIL_REQUEST'
export const GET_TIMESHEET_DETAIL_SUCCESS = 'GET_TIMESHEET_DETAIL_SUCCESS'
export const GET_TIMESHEET_DETAIL_FAILURE = 'GET_TIMESHEET_DETAIL_FAILURE'
// Add Time Sheet
export const ADD_TIMESHEETS_REQUEST = 'ADD_TIMESHEETS_REQUEST'
export const ADD_TIMESHEETS_SUCCESS = 'ADD_TIMESHEETS_SUCCESS'
export const ADD_TIMESHEETS_FAILURE = 'ADD_TIMESHEETS_FAILURE'
// Edit time sheet
export const EDIT_TIMESHEETS_REQUEST = 'EDIT_TIMESHEETS_REQUEST'
export const EDIT_TIMESHEETS_SUCCESS = 'EDIT_TIMESHEETS_SUCCESS'
export const EDIT_TIMESHEETS_FAILURE = 'EDIT_TIMESHEETS_FAILURE'
