export default {
  SplashScreen: 'SplashScreen',
  EmployerCode: 'EmployerCode',
  Login: 'Login',
  ForgotPassWord: 'ForgotPassWord',
  SetNewPassWord: 'SetNewPassWord',
  LoginWithTouchID: 'LoginWithTouchID',
  NewFeeds: 'NewFeeds',
  Message: 'Message',
  Home: 'Home',
  AuthStack: 'AuthStack',
  Notification: 'Notification',
  SignUp: 'SignUp',
  Profile: 'Profile',
}
