// List Company & personal
export const GET_COMPANY_PERSONAL_REQUEST = 'GET_COMPANY_PERSONAL_REQUEST'
export const GET_COMPANY_PERSONAL_SUCCESS = 'GET_COMPANY_PERSONAL_SUCCESS'
export const GET_COMPANY_PERSONAL_FAILURE = 'GET_COMPANY_PERSONAL_FAILURE'
// Personal Detail
export const GET_PERSONAL_DETAIL_REQUEST = 'GET_PERSONAL_DETAIL_REQUEST'
export const GET_PERSONAL_DETAIL_SUCCESS = 'GET_PERSONAL_DETAIL_SUCCESS'
export const GET_PERSONAL_DETAIL_FAILURE = 'GET_PERSONAL_DETAIL_FAILURE'
// Add Personal
export const ADD_DOCUMENT_REQUEST = 'ADD_DOCUMENT_REQUEST'
export const ADD_DOCUMENT_SUCCESS = 'ADD_DOCUMENT_SUCCESS'
export const ADD_DOCUMENT_FAILURE = 'ADD_DOCUMENT_FAILURE'
// Edit
export const EDIT_DOCUMENT_REQUEST = 'EDIT_DOCUMENT_REQUEST'
export const EDIT_DOCUMENT_SUCCESS = 'EDIT_DOCUMENT_SUCCESS'
export const EDIT_DOCUMENT_FAILURE = 'EDIT_DOCUMENT_FAILURE'
//  Company Detail
export const GET_COMPANY_DETAIL_REQUEST = 'GET_COMPANY_DETAIL_REQUEST'
export const GET_COMPANY_DETAIL_SUCCESS = 'GET_COMPANY_DETAIL_SUCCESS'
export const GET_COMPANY_DETAIL_FAILURE = 'GET_COMPANY_DETAIL_FAILURE'
