
export const GET_AUTHORISATION_REQUEST = 'GET_AUTHORISATION_REQUEST'
export const GET_AUTHORISATION_SUCCESS = 'GET_AUTHORISATION_SUCCESS'
export const GET_AUTHORISATION_FAILURE = 'GET_AUTHORISATION_FAILURE'
// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
// Logout
export const LOGOUT = 'LOGOUT'
