
export const GET_OPTION_LIST_REQUEST = 'GET_OPTION_LIST_REQUEST'
export const GET_OPTION_LIST_SUCCESS = 'GET_OPTION_LIST_SUCCESS'
export const GET_OPTION_LIST_FAILURE = 'GET_OPTION_LIST_FAILURE'
// Assignment
export const GET_ASSIGNMENT_LIST_REQUEST = 'GET_ASSIGNMENT_LIST_REQUEST'
export const GET_ASSIGNMENT_LIST_SUCCESS = 'GET_ASSIGNMENT_LIST_SUCCESS'
export const GET_ASSIGNMENT_LIST_FAILURE = 'GET_ASSIGNMENT_LIST_FAILURE'
// Agency
export const GET_AGENCY_LIST_REQUEST = 'GET_AGENCY_LIST_REQUEST'
export const GET_AGENCY_LIST_SUCCESS = 'GET_AGENCY_LIST_SUCCESS'
export const GET_AGENCY_LIST_FAILURE = 'GET_AGENCY_LIST_FAILURE'
