
// Message
export const GET_MESSAGE_REQUEST = 'GET_MESSAGE_REQUEST'
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS'
export const GET_MESSAGE_FAILURE = 'GET_MESSAGE_FAILURE'
// Message Detail
export const GET_MESSAGE_DETAIL_REQUEST = 'GET_MESSAGE_DETAIL_REQUEST'
export const GET_MESSAGE_DETAIL_SUCCESS = 'GET_MESSAGE_DETAIL_SUCCESS'
export const GET_MESSAGE_DETAIL_FAILURE = 'GET_MESSAGE_DETAIL_FAILURE'
// ADD Message Compose
export const ADD_MESSAGE_COMPOSE_REQUEST = 'ADD_MESSAGE_COMPOSE_REQUEST'
export const ADD_MESSAGE_COMPOSE_SUCCESS = 'ADD_MESSAGE_COMPOSE_SUCCESS'
export const ADD_MESSAGE_COMPOSE_FAILURE = 'ADD_MESSAGE_COMPOSE_FAILURE'
// Add Document
export const ADD_MESSAGE_COMPOSE_DOCUMENT_REQUEST = 'ADD_MESSAGE_COMPOSE_DOCUMENT_REQUEST'
export const ADD_MESSAGE_COMPOSE_DOCUMENT_SUCCESS = 'ADD_MESSAGE_COMPOSE_DOCUMENT_SUCCESS'
export const ADD_MESSAGE_COMPOSE_DOCUMENT_FAILURE = 'ADD_MESSAGE_COMPOSE_DOCUMENT_FAILURE'
