// Profile
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST'
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS'
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE'
// Update Profile
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE'
// Get Bank Detail
export const GET_BANK_REQUEST = 'GET_BANK_REQUEST'
export const GET_BANK_SUCCESS = 'GET_BANK_SUCCESS'
export const GET_BANK_FAILURE = 'GET_BANK_FAILURE'
// Update Bank Detail
export const UPDATE_BANK_REQUEST = 'UPDATE_BANK_REQUEST'
export const UPDATE_BANK_SUCCESS = 'UPDATE_BANK_SUCCESS'
export const UPDATE_BANK_FAILURE = 'UPDATE_BANK_FAILURE'
// Get HMMRC Detail
export const GET_HMRC_REQUEST = 'GET_HMRC_REQUEST'
export const GET_HMRC_SUCCESS = 'GET_HMRC_SUCCESS'
export const GET_HMRC_FAILURE = 'GET_HMRC_FAILURE'
// Get Payroll Detail
export const GET_PAYROLL_REQUEST = 'GET_PAYROLL_REQUEST'
export const GET_PAYROLL_SUCCESS = 'GET_PAYROLL_SUCCESS'
export const GET_PAYROLL_FAILURE = 'GET_PAYROLL_FAILURE'
// Get Attach orders
export const GET_ATTACHMENTORDERS_REQUEST = 'GET_ATTACHMENTORDERS_REQUEST'
export const GET_ATTACHMENTORDERS_SUCCESS = 'GET_ATTACHMENTORDERS_SUCCESS'
export const GET_ATTACHMENTORDERS_FAILURE = 'GET_ATTACHMENTORDERS_FAILURE'
// Get SMP
export const GET_SMP_REQUEST = 'GET_SMP_REQUEST'
export const GET_SMP_SUCCESS = 'GET_SMP_SUCCESS'
export const GET_SMP_FAILURE = 'GET_SMP_FAILURE'
// Get SMP Detail
export const GET_SMP_DETAIL_REQUEST = 'GET_SMP_DETAIL_REQUEST'
export const GET_SMP_DETAIL_SUCCESS = 'GET_SMP_DETAIL_SUCCESS'
export const GET_SMP_DETAIL_FAILURE = 'GET_SMP_DETAIL_FAILURE'
