
export const GET_ASSIGNMENTS_REQUEST = 'GET_ASSIGNMENTS_REQUEST'
export const GET_ASSIGNMENTS_SUCCESS = 'GET_ASSIGNMENTS_SUCCESS'
export const GET_ASSIGNMENTS_FAILURE = 'GET_ASSIGNMENTS_FAILURE'
// Asignment Detail

export const GET_ASSIGNMENT_DETAIL_REQUEST = 'GET_ASSIGNMENT_DETAIL_REQUEST'
export const GET_ASSIGNMENT_DETAIL_SUCCESS = 'GET_ASSIGNMENT_DETAIL_SUCCESS'
export const GET_ASSIGNMENT_DETAIL_FAILURE = 'GET_ASSIGNMENT_DETAIL_FAILURE'
// Rates
export const GET_RATES_REQUEST = 'GET_RATES_REQUEST'
export const GET_RATES_SUCCESS = 'GET_RATES_SUCCESS'
export const GET_RATES_FAILURE = 'GET_RATES_FAILURE'
